---
title: Drive
documents:
- cover.html
- sequencier.html
- traitement.html
- synopsis.html
book_infos:
  author: Philippe Perret
  publisher:
    name: Éditions Icare
    logo: img/icare-editions.png
  cover:
    path: img/Drive-cover-prov.jpg
    width: 15cm
    height: 379px
    left: 0.5cm
title_fr:
video:
  width: 600
  name: output.mp4
  original_path: "/Volumes/BackupPlusDrive/AnalyseFilms-videos/Drive-subtitles.mp4"
video2:
  width: 200
options:
  video_follows_mouse: false
  follow_selected_event: true
  show_current_event: false
  synchro_videos_on_stop: true
  memorize_last_time: true
personnages:
  PR: Chauffeur cascadeur
  EL: Femme du tôlard
  PG: Patron du garage
  CM: Chef mafieu
  CLIENTS:
    full_name: deux clients de PR
    short_name: deux clients
    nick_name: clients
decors:
  immeuble:
    hname: Immeuble PR
    items:
      appartPR: Appartement de PR
      appartEL: Appartement de EL
      parking: Parking
      ascenseur: Ascenseur
  garage: Garage du PG
  ville:
    hname: Ville
    items:
      rues: Rues
  parking: Parking public souterrain
  tournage:
    hname: Plateau de tournage
    items:
      maquillage: maquillage
      plateau: Plateau
      voiture: Voiture
  casse: Lieu du casse
film_folder: Drive
last_time: 5751
:film_folder: Drive
last_selected_event: 2
