---
video:
  width: 600
  name: Drive_720p.mp4
video2:
  width: 200
options:
  video_follows_mouse: false
  follow_selected_event: true
  show_current_event: false
personnages:
  PR: Protagoniste
  AN: Antagoniste
  OQ: Objet de la quête
film_folder: Drive
