---
title: Drive
resume: '<span class="film">Drive</span> raconte l''histoire d''un chauffeur doué,
  travaillant comme cascadeur.

  '
isbn: XX-X-XXXXX-XXX-XX
prix: 5 €
documents:
- cover.html
- frontispice.html
- sequencier.html
documents_out:
- traitement.html
- synopsis.html
- composition.html
- quatrieme.html  
book_infos:
  copyright: Tous droits de reproduction, d'adaptation et de traduction réservés
  author:
    name: Philippe Perret
    cv: Philippe Perret est romancier publié à compte d'éditeur, scénariste professionnel,
      musicien, pédagogue (www.atelier-icare.net).
    books: "mort@vivant, Cloaca Maxima, collection « Passé sous silence »"
  publisher:
    name: Éditions Icare
    address: https://www.atelier-icare.net
    logo: img/icare-editions.png
  depot_legal: MM AAAA
  imprimeur:  Lulu la tortue
  print_date: MM AAAA
  cover:
    path: img/Drive-cover-prov.jpg
    width: 15cm
    height: 379px
    left: 0.5cm
    top: 0
  cover4:
    img_path: img/Drive-cover-prov.jpg
    img_width: 10cm
    img_height: auto
    img_left: 0
    img_top: 0
title_fr:
video:
  width: 600
  name: output.mp4
  original_path: "/Volumes/BackupPlusDrive/AnalyseFilms-videos/Drive-subtitles.mp4"
video2:
  width: 200
options:
  video_follows_mouse: false
  follow_selected_event: true
  show_current_event: false
  synchro_videos_on_stop: true
  memorize_last_time: true
personnages:
  PR: Chauffeur cascadeur
  EL: Femme du tôlard
  PG: Patron du garage
  CM: Chef mafieu
  CLIENTS:
    full_name: deux clients de PR
    short_name: deux clients
    nick_name: clients
decors:
  immeuble:
    hname: Immeuble PR
    items:
      appartPR: Appartement de PR
      appartEL: Appartement de EL
      parking: Parking
      ascenseur: Ascenseur
  garage: Garage du PG
  ville:
    hname: Ville
    items:
      rues: Rues
  parking: Parking public souterrain
  tournage:
    hname: Plateau de tournage
    items:
      maquillage: maquillage
      plateau: Plateau
      voiture: Voiture
  casse: Lieu du casse
film_folder: Drive
last_time: 5751
:film_folder: Drive
last_selected_event: 2
